---
name: Python package

'on':
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Build wheel
        run: uv build --wheel

      - name: Publish to pypi
        run: uv publish -u __token__ -p ${{ secrets.PYPI_TOKEN }}

      - name: Publish aur
        uses: pyazo-screenshot/docker_action@v1
        with:
          tag: ${{ github.ref }}
          aur_key: ${{ secrets.AUR_KEY }}
